// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
void main() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPMELNkaHdc0ZR7C9xnxw29bmFIV-gi8Q',
    appId: '1:742804854739:web:84bbeb70ad994b09bc0126',
    messagingSenderId: '742804854739',
    projectId: 'tune-clash',
    authDomain: 'tune-clash.firebaseapp.com',
    storageBucket: 'tune-clash.appspot.com',
    measurementId: 'G-YWFF36WSEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuUeH4cT83xeje-AZzf_D6oroIo-B7kyI',
    appId: '1:742804854739:android:d4d563baf1d99c13bc0126',
    messagingSenderId: '742804854739',
    projectId: 'tune-clash',
    storageBucket: 'tune-clash.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD72r7QL61Cpyg2je2do4V2Vtd0dnxBuOk',
    appId: '1:742804854739:ios:dd7bc113be763065bc0126',
    messagingSenderId: '742804854739',
    projectId: 'tune-clash',
    storageBucket: 'tune-clash.appspot.com',
    iosClientId: '742804854739-e7acer9s708mdeeptf60nqkkktqbr5hv.apps.googleusercontent.com',
    iosBundleId: 'com.example.tuneClash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD72r7QL61Cpyg2je2do4V2Vtd0dnxBuOk',
    appId: '1:742804854739:ios:dd7bc113be763065bc0126',
    messagingSenderId: '742804854739',
    projectId: 'tune-clash',
    storageBucket: 'tune-clash.appspot.com',
    iosClientId: '742804854739-e7acer9s708mdeeptf60nqkkktqbr5hv.apps.googleusercontent.com',
    iosBundleId: 'com.example.tuneClash',
  );
}
